version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Print node install help instructions
          command: |
            echo "One cause for node package install failure is if you have private repositories that it can't reach"
            echo "One way to fix this for private npm packages:"
            echo "  1. Use the npm CLI's 'login' command to create a token (usually saved in your user's '~/.npmrc' file)"
            echo "     For more info, see https://circleci.com/blog/publishing-npm-packages-using-circleci-2-0/#:~:text=set%20the%20%24npm_token%20environment%20variable%20in%20circleci"
            echo "  2. Add an NPM_TOKEN to an org context"
            echo "     For info on how to use contexts, see https://circleci.com/docs/contexts/"
            echo "  3. Add a '.circleci/config.yml' to your repository or use this config.yml as a starting template"
            echo "  4. Configure the jobs to use the context that includes NPM_TOKEN"
            echo "  5. Add a step to inject your NPM_TOKEN environment variable into npm before 'install-packages'"
            echo "     For an example, see https://circleci.com/blog/publishing-npm-packages-using-circleci-2-0/#:~:text=the%20deploy%20job%20has%20several%20steps%20that%20run%20to%20authenticate%20with%20and%20publish%20to"
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      # Copy output to artifacts dir
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build
    when: on_fail

      - run:
          name: Send Discord Notification
          command: |
            DISCORD_WEBHOOK_URL="https://discord.com/api/webhooks/1203163354680655902/OnCfXS-HFyfVYeWglQPR_EJA6HzzRLurRgDt7P0RwPvPUxkea6Z-ncp4AoffsRsWMVB0"
            curl -X POST -H "Content-Type: application/json" -d '{
              "content": "Build Status: '"$CIRCLE_BUILD_URL"'",
              "embeds": [
                {
                  "title": "Build Details",
                  "fields": [
                    {
                      "name": "Branch",
                      "value": "'"$CIRCLE_BRANCH"'"
                    },
                    {
                      "name": "Status",
                      "value": "'"$CIRCLE_STATUS"'"
                    }
                  ]
                }
              ]
            }' $DISCORD_WEBHOOK_URL
workflows:
  version: 2
  build:
    jobs:
      - build-node
