import Page from "@/assets/_UI/Page";

export default function PrivacyPolicy(){
    return <Page className="flex flex-col gap-y-4 md:gap-y-24">
      <div className="px-6">
        <p className="text-5xl text-center decoration-solid font-extrabold bg-gray-light h-72 flex justify-center items-center">Privacy Policy</p>
        <p>This Privacy Policy was last updated on February 23, 2024.</p>
        <p className="text-2xl decoration-solid font-extrabold">What does this policy cover</p>
        <p className="indent-8">Welcome to CareerHub, the online and mobile service of CareerHub. Our Privacy Policy explains how CareerHub and its affiliates collect, use, disclose, and protect information that applies to our visual communication platform (the "Service"), and your choices about the collection and use of your information. Capitalized terms that are not defined in this Privacy Policy have the meaning given to them in our Terms of Use(opens in a new tab or window). If you do not want your information processed in accordance with this Privacy Policy in general or any part of it, you should not use our Service. This policy applies to all users of the Service, including, but not limited to users of our Developer Portal(opens in a new tab or window).</p>
        <p className="text-2xl decoration-solid font-extrabold">1. Information we collect</p>
        <p className="indent-8decoration-solid font-extrabold" >(a) Information you provide us directly</p>
        <p className="indent-8">We may ask for certain information when you register for a CareerHub account or correspond with us (such as a username, your first and last names, birthdate, phone number, profession, physical and e-mail address). We also collect any messages you send us through the Service (such as user feedback, search queries and prompts), and may collect information you provide in User Content you post to the Service (such as text and photos you upload to use in your designs). We use this information to operate, maintain, improve and provide the features and functionality of the Service to you, to correspond with you, and to address any issues you raise about the Service. If you don’t provide your personal information to us, you may not be able to access or use our Service or your experience of using our Service may not be as enjoyable.</p>
        <p className="decoration-solid font-extrabold">(b) Information we receive from third-party applications</p>
        <p className="indent-8">We may receive information about you from third parties. For example, if you access the Service through a third-party connection or log-in, such as Facebook Connect, by “following,” “liking,” adding the CareerHub application, linking your account to the CareerHub Service, etc., that third party may pass certain information about your use of its service to CareerHub. This information could include, but is not limited to, the user ID associated with your account (for example, your Facebook UID), an access token necessary to access that service, any information that you have permitted the third party to share with us, and any information you have made public in connection with that service. You should always review, and if necessary, adjust your privacy settings on third-party websites and services before linking or connecting them to the Service. You may also unlink your third party account from the Service by adjusting your settings on the third party service. If you unlink your third party account, we will no longer receive information collected about you in connection with that service. And if you choose to integrate with a third party application to incorporate elements into your designs, enhance media, supercharge your workflow or share to social media, we could receive data from such apps (as well as disclose data to such apps). If you communicate with us via social media, including Instagram, Facebook or TikTok and choose to share your user generated content with us, we may receive information such as videos you’ve created, your photo, your account name and your comments about CareerHub.</p>
        <p className="decoration-solid font-extrabold">(c)Information we receive from other third parties</p>
        <p className="indent-8">We may obtain information about you from third-party sources, such as public sources, social media platforms (like Facebook, Instagram, LinkedIn, Twitter and other platforms) and third-party data providers and information services. Examples of the information we may obtain from such third parties include your company, company size, job title and seniority, industry and other profile information. We may share your email address or other information in order to obtain and combine this information with information that you provide to us or other information that we collect when you use our Service. We do this to better understand your profile and interests so that we can deliver customized offers and other personalized services to you, such as to serve relevant offers to you via email, chatbots, phone or personalized advertising. You can opt out of CareerHub collecting more data about you from third-party providers to tailor your experience and messages we send you here(opens in a new tab or window).
          Some of these providers may combine data collected from our Service through cookies, pixels, tags and similar technologies, with email or mailing addresses to which they have access to help us serve relevant offers to you.
          If you are not a CareerHub subscriber, we may obtain your contact details from a social media platform, such as LinkedIn, or a third party data provider, so that we can promote our product offerings and subscriptions to you if we think they would be helpful in your role.
          We also may have obtained your details from another CareerHub user, for example when they have shared a design with you.
          We may also receive information about you and your engagement with our advertisements from our ad servers, ad networks and social media platforms. This may include the websites you visited before coming to CareerHub so that we can determine advertising effectiveness and pay our referral partners.
          If you prefer not to have your information used for this purpose, you can opt out at any time by emailing us at privacy@CareerHub.com.
          CareerHub for Education: Please note that references to utilizing third-party information for offers and advertising in this Section 1(c) do not apply to students using CareerHub for Education. We do not serve advertising to students using CareerHub for Education.</p>
        <p className="decoration-solid font-extrabold">(d) Information we collect from you automatically</p>
        <p className="indent-8">We will directly collect or generate certain information about your use of the Service (such as user activity data, analytics event data, and clickstream data) for data analytics and machine learning, and to help us measure traffic and usage trends for the Service. We may also use third party analytics tools that automatically collect information sent by your browser or mobile device, including the pages you visit and other information , that assists us in improving the Service. For more information, please see the paragraphs below on cookies information, log file information, clear gifs, device identifiers, and location data.</p>
        <p className="decoration-solid font-extrabold">(e) Cookies information and information taken from similar technologies</p>
        <p className="indent-8">When you visit the Service, we (and our third-party partners) will send cookies — small text files containing a string of alphanumeric characters — to your computer that uniquely identifies your browser and lets CareerHub do things like help you log in faster, enhance your navigation through the site, remember your preferences and generally improve the user experience. Cookies also convey information to us about how you use the Service (e.g., the pages you view, the links you click and other actions you take on the Service), and allow us or our business partners to track your usage of the Service over time. They also allow us to measure traffic and usage trends for the Service, deliver personalized advertisements that may be of interest to you and measure their effectiveness, and find potential new users of the Service.You can control or reset your cookies and similar technologies through your web browser, which will allow you to customize your cookie preferences and to refuse all cookies or to indicate when a cookie is being sent. However, some features of the Service may not function properly if the ability to accept cookies is disabled. For more information on how we use cookies and other technologies and how you can control them, please read our Cookies Policy(opens in a new tab or window).CareerHub for Education: Please note that references to utilizing cookies for advertising in this Section 1(e) do not apply to students using "CareerHub for Education" - we do not serve advertising to students using CareerHub for Education.</p>
        <p className="decoration-solid font-extrabold">(f) Log file information</p>
        <p className="indent-8">Log file information is automatically reported by your browser or mobile device each time you access the Service. When you use our Service, our servers automatically record certain log file information. These server logs may include anonymous information such as your web request, browser type, referring / exit pages and URLs, number of clicks and how you interact with links on the Service, domain names, landing pages, pages viewed, and other such information.</p>
        <p className="decoration-solid font-extrabold">(g) Clear gifs/web beacons information</p>
        <p className="indent-8">When you use the Service, we may employ clear GIFs (also known as web beacons) which are used to anonymously track the online usage patterns of our users. In addition, we may also use clear GIFs in HTML-based emails sent to our users to track which emails are opened and which links are clicked by recipients. This information allows for more accurate reporting and improvement of the Service.</p>
        <p className="decoration-solid font-extrabold">(h) Device identifiers</p>
        <p className="indent-8">When you access the Service on a device (including smart-phones or tablets), we may access, collect and/or monitor one or more “device identifiers,” such as a universally unique identifier (“UUID”). Device identifiers are small data files that uniquely identify your mobile device. A device identifier may convey information to us about how you use the Service. A device identifier may remain persistently on your device, to help you log in and navigate the Service better. Some features of the Service may not function properly if use of device identifiers is impaired. Device Identifiers used by CareerHub include the Android Advertising ID and iOS Advertising Identifier.</p>
        <p className="decoration-solid font-extrabold">(i) Location data</p>
        <p className="indent-8">CareerHub collects information in order to understand where its users are located for a number of reasons. It helps CareerHub to localize and personalize content, comply with local laws, undertake aggregated analytics, understand if its users use CareerHub for domestic, business or educational use, improve advertising efficiency and estimate the tax liability of CareerHub.
          <br></br>CareerHub may collect your precise or approximate location:
          <br></br>- from you, when you provide, correct or confirm your location (e.g., when you purchase products from us);
          <br></br>- by inferring your location from your IP address; and
          <br></br>- from our partners or your payment provider.
          <br></br>CareerHub for Education: Please note that references to advertising in this Section 1(i) do not apply to students using CareerHub for Education - we do not serve advertising to students using CareerHub for Education.</p>       
      
        <p className="text-2xl decoration-solid font-extrabold">2. How we use your information</p>
        <p>We use the information we collect about you for the purposes set out below:</p>
        <li><strong>Providing you with the Service:</strong> We use the information that you directly give us to provide the Service to you. This includes allowing you to log in to CareerHub, operating and maintaining the Service, giving you access to your designs and billing you for transactions that you make via the Service. We also use information we collect about you automatically to remember information about you so that you will not have to re-enter it during your visit or the next time you visit the site.</li>
        <li><strong>For data analytics:</strong> We use information about you to help us improve the CareerHub Service and our users’ experience, including by monitoring aggregate metrics such as total number of visitors, traffic, and demographic patterns.</li>
        <li><strong>For Service improvement (including analytics and machine learning):</strong>We may analyze your activity, content, media uploads and related data in your account to provide and customize the Service, and to train our algorithms, models and AI products and services using machine learning to develop, improve and provide our Service. You can manage the use of your data for training AI to improve our Service in the privacy settings page under your account settings(opens in a new tab or window).</li>
        <li><strong>Customizing the Service for you:</strong>We use and combine the information you provide us and information about you that we collect automatically and receive from other sources (including information we receive on and off our Service) and combine it with information about the behavior of other users to make sure that your use of the Service is customized to your needs. For example, to recommend templates, ingredients and fonts that are likely to be useful to you in a design, we may use information derived from your prior behavior on our Service, the use of these elements by other people working on similar designs and other inferred information.</li>
        <li><strong>To communicate with you about the Service:</strong>We use your contact information to get in touch with you and to send communications about critical elements of the Service. For example, we may send you emails about technical issues, security alerts or administrative matters.</li>
        <li><strong>To promote and drive engagement with the CareerHub Service:</strong>We use your contact information to get in touch with you about taking part in our surveys or about features and offers relating to the Service that we think you would be interested in. We also use information we collect about you to make sure that you get the most relevant offers and promotions based on your use of the Service, and your preferences. You can opt-out of these communications as described below.</li>
        <li><strong>For advertising purposes:</strong>We use information about you, including cookies information and other information we (and our third-party partners) collect from you automatically about your use of the Service, to serve, personalize and measure the effectiveness of advertising on the Service and third-party sites and platforms. This includes showing you advertising we think you might find interesting as well as displaying advertising to potential new users that have similar interests. Please note that we do not serve advertising to students using CareerHub for Education. For more details about how we use your information for advertising purposes, please see Section 4 “Advertising”.</li>
        <li><strong>Customer happiness: </strong>We use information about you, information that we collect or and from within your account, information that you provide to our customer happiness team, and information about your interactions with the Service to resolve technical issues you experience with the Service, and to ensure that we can repair and improve the Service for all CareerHub users.</li>
        <li><strong>For safety, security, fraud and abuse measures:</strong>We may use information about you, your activity, content, media uploads and related data in your account to prevent, detect, investigate and address safety, security, fraud and abuse risks, and to develop our algorithms and models to identify violations of this Privacy Policy, our Terms of Use(opens in a new tab or window) or our Acceptable Use Policy(opens in a new tab or window) (e.g., detecting content such as pornographic or copyright protected material).</li>
        <li><strong>For matters that you have specifically consented to:</strong>From time to time CareerHub may seek your consent to use your information for a particular purpose. Where you consent to our doing so, we will use it for that purpose. Where you no longer want us to use your information for that purpose you may withdraw your consent to this use.</li>
        <li><strong>For troubleshooting, error resolution and service improvement:</strong>We may need to review your designs to support your request for help, correct general errors with the CareerHub Service or improve our services.</li>
        <li><strong>For matters that we are required to use your information by law: </strong>CareerHub will use or disclose your information where we reasonably believe that such action is necessary to (a) comply with the law and the reasonable requests of law enforcement; (b) to enforce our Terms of Use(opens in a new tab or window) and our Acceptable Use Policy(opens in a new tab or window) or to protect the security or integrity of our Service; and/or (c) to exercise or protect the rights, property, or personal safety of CareerHub, our users or others.</li>
        <p className="text-2xl decoration-solid font-extrabold">3. How we transfer, store and protect your data</p>
        <p className="indent-8">Your information collected through the Service will be stored and processed in the United States, Australia, Singapore, European Union, United Kingdom, Philippines and New Zealand and any other country in which CareerHub or its subsidiaries, affiliates or service providers maintain facilities or employ staff or contractors. CareerHub transfers information that we collect about you, including personal information, to affiliated entities, and to other third parties across borders and from your country or jurisdiction to other countries or jurisdictions around the world. As a result, we may transfer information, including personal information, to a country and jurisdiction that does not have the same data protection laws as your jurisdiction. However, we always take steps to ensure that your information remains protected wherever it is stored and processed in accordance with applicable laws. Where required under applicable laws, you consent to the transfer of information to the U.S. or any other country in which CareerHub or its parent, subsidiaries, affiliates or service providers maintain facilities and the use and disclosure of information about you as described in this Privacy Policy.CareerHub’s U.S. subsidiary adheres to compliance with the EU-U.S. Data Privacy Framework, the Swiss-U.S. Data Privacy Framework and the UK Extension to the EU-U.S. Data Privacy Framework. You can learn more about these frameworks, including your rights under each program, in our Data Privacy Framework Statement(opens in a new tab or window).</p>
        <p className="text-2xl decoration-solid font-extrabold">4. Keeping your information safe</p>
        <p className="indent-8">CareerHub cares about the security of your information, and uses appropriate safeguards to preserve the integrity and security of all information collected through the Service. To protect your privacy and security, we take reasonable steps (such as requesting a unique password) to verify your identity before granting you access to your account. You are responsible for maintaining the secrecy of your unique password and account information, and for controlling access to your email communications from CareerHub, at all times. However, CareerHub cannot ensure or warrant the security of any information you transmit to CareerHub or guarantee that information on the Service may not be accessed, disclosed, altered, or destroyed. Your privacy settings may also be affected by changes to the functionality of third party sites and services that you add to the CareerHub Service, such as social networks. CareerHub is not responsible for the functionality or security measures of any third party.
          <br></br>For more information about CareerHub security, please visit Security at CareerHub(opens in a new tab or window).</p>
        <p className="text-2xl decoration-solid font-extrabold">5. Changes to this Policy</p>
        <p className="indent-8">We may update this policy from time to time to reflect our current practice and ensure compliance with applicable laws. When we post changes to this policy, we will revise the “Last Updated” date at the top of this policy. If we make any material changes to the way we collect, use, store and/or share your personal information, we will notify you on our website or by sending an email to the email address associated with your CareerHub account. We recommend that you check this page from time to time to inform yourself of any changes.</p>
      </div>
  </Page>
}